apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsa-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dsa
  template:
    metadata:
      labels:
        app: dsa
    spec:
      containers:
      - name: dsa-container
        image: gcr.io/your-project-id/dsa-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dsa-service
spec:
  type: LoadBalancer
  selector:
    app: dsa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
